### ISSUE TITLE
[BUG] Error while using rollup

### ISSUE THREAD

**Issue by gfortin6** [ReactTooltip/react-tooltip#1069]
**Bug description**
I created a React library that is using your library and when I build my lib using Rollup I get that error message
    ```[!] RollupError: "default" is not exported by "node_modules/classnames/index.js", imported by "node_modules/react-tooltip/dist/react-tooltip.min.mjs".
    https://rollupjs.org/troubleshooting/#error-name-is-not-exported-by-module
    node_modules/react-tooltip/dist/react-tooltip.min.mjs (7:156)
    5: * @license MIT
    6: */
    7: import e,{createContext as t,useState as r,useCallback as o,useMemo as n,useContext as l,useRef as c,useEffect as i,useLayoutEffect as s}from"react";import a from"cla...
                                                                                                                                                                   ^
    8: .styles-module_tooltip__mnnfp{padding:8px 16px;border-radius:3px;font-size:90%;width:max-content}.styles-module_arrow__K0L3T{width:8px;height:8px;transform:rotate(45d...
        at error (/Users/guillaumefortin/gitADS/ads-react-component-lib/node_modules/rollup/dist/shared/rollup.js:349:30)
        at Module.error (/Users/guillaumefortin/gitADS/ads-react-component-lib/node_modules/rollup/dist/shared/rollup.js:15073:16)
        at Module.traceVariable (/Users/guillaumefortin/gitADS/ads-react-component-lib/node_modules/rollup/dist/shared/rollup.js:15498:29)
        at ModuleScope.findVariable (/Users/guillaumefortin/gitADS/ads-react-component-lib/node_modules/rollup/dist/shared/rollup.js:14023:39)
        at ReturnValueScope.findVariable (/Users/guillaumefortin/gitADS/ads-react-component-lib/node_modules/rollup/dist/shared/rollup.js:8583:38)
        at ChildScope.findVariable (/Users/guillaumefortin/gitADS/ads-react-component-lib/node_modules/rollup/dist/shared/rollup.js:8583:38)
        at Identifier.bind (/Users/guillaumefortin/gitADS/ads-react-component-lib/node_modules/rollup/dist/shared/rollup.js:9743:40)
        at CallExpression.bind (/Users/guillaumefortin/gitADS/ads-react-component-lib/node_modules/rollup/dist/shared/rollup.js:7363:23)
        at CallExpression.bind (/Users/guillaumefortin/gitADS/ads-react-component-lib/node_modules/rollup/dist/shared/rollup.js:11309:15)
        at Property.bind (/Users/guillaumefortin/gitADS/ads-react-component-lib/node_modules/rollup/dist/shared/rollup.js:7363:23)
    ```

**Version of Package**
v5.19.0 but i tried older version and i get the same issue

**Expected behavior**
The rollup build is passing without issue

**Desktop (please complete the following information if possible or delete this section):**
 - Frameworks [ React 18.2.0,Rollup 3.26.3]

**Comment by danielbarion** [comment]
@gfortin6 do you have the `classnames` package in your project? 

https://www.npmjs.com/package/classnames

**Comment by gfortin6** [comment]
I tried with and without that package and i get the a same error

**Comment by gfortin6** [comment]
of course, i'll do a quick sample for you guys tomorrow and i'll share it thanks

**Comment by gfortin6** [comment]
Here's the sample project
https://github.com/gfortin6/sampleReactTooltip
just have to do a `npm install` and then a `rollup`

**Comment by danielbarion** [comment]
It's not an error with ReactTooltip but with your configuration. Please try adding the following package and let me know if it works:

![image](https://github.com/ReactTooltip/react-tooltip/assets/9615850/fc47f50a-7c97-4c47-a6e7-3668daf1e0ec)
![image](https://github.com/ReactTooltip/react-tooltip/assets/9615850/eab30e81-787c-4cee-85a3-6e51be9a85c6)
![image](https://github.com/ReactTooltip/react-tooltip/assets/9615850/0d3bb752-112f-4ff1-ae23-c1afb2d6d427)

**Comment by gfortin6** [comment]
Hi Daniel, it worked. very sorry for my mistake
thanks to you
