### ISSUE TITLE
Error on `injectStyles`:  "Failed to execute 'appendChild' on 'Node': Only one element on document allowed."

### ISSUE THREAD

**Issue by andreiho** [ReactTooltip/react-tooltip#673]
Possibly related: https://github.com/wwayne/react-tooltip/issues/669

```
DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
    at ReactTooltip.injectStyles (webpack-internal:///cpGi:1195:17)
    at ReactTooltip.injectStyles (webpack-internal:///wssv:717:25)
    at ReactTooltip.componentDidMount (webpack-internal:///cpGi:1149:12)
    at ReactTooltip.componentDidMount (webpack-internal:///wssv:707:123)
    at commitLifeCycles (webpack-internal:///fxOa:20659:24)
    at commitLayoutEffects (webpack-internal:///fxOa:23422:7)
    at HTMLUnknownElement.callCallback (webpack-internal:///fxOa:3946:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///fxOa:3995:16)
    at invokeGuardedCallback (webpack-internal:///fxOa:4057:31)
    at commitRootImpl (webpack-internal:///fxOa:23147:9) "
    at AppContainer (eval at ES6ProxyComponentFactory (webpack-internal:///wssv), <anonymous>:14:7)
    at HotExportedRoot (eval at ES6ProxyComponentFactory (webpack-internal:///wssv), <anonymous>:14:7)"
```

**Comment by ayusshar** [comment]
Getting Kind of similar error

> console.error node_modules/jest-environment-jsdom-sixteen/node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Uncaught [HierarchyRequestError: Invalid insertion of STYLE node in #document node.]
          at reportException (/home/ubuntuadmin/agent/_work/94/s/node_modules/jest-environment-jsdom-sixteen/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
          at innerInvokeEventListeners (/home/ubuntuadmin/agent/_work/94/s/node_modules/jest-environment-jsdom-sixteen/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:333:9)
          at invokeEventListeners (/home/ubuntuadmin/agent/_work/94/s/node_modules/jest-environment-jsdom-sixteen/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
          at HTMLUnknownElementImpl._dispatch (/home/ubuntuadmin/agent/_work/94/s/node_modules/jest-environment-jsdom-sixteen/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
          at HTMLUnknownElementImpl.dispatchEvent (/home/ubuntuadmin/agent/_work/94/s/node_modules/jest-environment-jsdom-sixteen/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
          at HTMLUnknownElement.dispatchEvent (/home/ubuntuadmin/agent/_work/94/s/node_modules/jest-environment-jsdom-sixteen/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
          at Object.invokeGuardedCallbackDev (/home/ubuntuadmin/agent/_work/94/s/node_modules/react-dom/cjs/react-dom.development.js:237:16)
          at invokeGuardedCallback (/home/ubuntuadmin/agent/_work/94/s/node_modules/react-dom/cjs/react-dom.development.js:292:31)
          at commitRootImpl (/home/ubuntuadmin/agent/_work/94/s/node_modules/react-dom/cjs/react-dom.development.js:22541:9)
          at unstable_runWithPriority (/home/ubuntuadmin/agent/_work/94/s/node_modules/scheduler/cjs/scheduler.development.js:653:12) DOMException {}
    console.error node_modules/react-dom/cjs/react-dom.development.js:19527
      The above error occurred in the <ReactTooltip> component:

**Comment by sumthief** [comment]
Sad to hear new version still break things :confused:

@andreiho It would be great if you can provide more details about your use case.

@ayusshar please could you give more details about failing test?

Maybe you can provide minimal reproducible repository?

**Comment by jryd** [comment]
@sumthief I am getting the same error as @ayusshar and can provide a reproducible example:

`Attribution.js`
```
import React from 'react';
import ReactTooltip from 'react-tooltip';

const Example = () => {
  return <div>
    <p className="text-xs font-semibold uppercase tracking-wide text-gray-500 mb-2">Example</p>
    <div className="flex flex-wrap -m-8">
        <div className="p-8" data-testid="example" data-tip="This is a test <br/> and it doesn't work">
          <p className="text-xs text-gray-700">Example paragraph</p>
        </div>
    </div>
    <ReactTooltip multiline={true}/>
  </div>
};

export default Example;
```

`Example.test.js`
```
import React from 'react';
import { render } from '@testing-library/react';
import Attribution from './Example';
import ReactTooltip from 'react-tooltip';

describe('Example', () => {
  it('can render', () => {
    render(<Example />);
  });

  it('can render standalone', () => {
    render(<ReactTooltip multiline={true} />);
  });
});
```

**Comment by mumarm45** [comment]
Getting the same error while running the test.

**Comment by yakabay** [comment]
> Getting the same error while running the test.
I'm also getting errors in my test for react-tooltip 4.2.14 (I'm using React Testing Library):

`console.error
Error: Uncaught [HierarchyRequestError: Invalid insertion of STYLE node in #document node.]
at reportException (.../node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
at innerInvokeEventListeners (.../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:333:9)
at invokeEventListeners (.../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
at HTMLUnknownElementImpl._dispatch (.../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
at HTMLUnknownElementImpl.dispatchEvent (.../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
at HTMLUnknownElement.dispatchEvent (.../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
at Object.invokeGuardedCallbackDev (.../node_modules/react-dom/cjs/react-dom.development.js:3994:16)
at invokeGuardedCallback (.../node_modules/react-dom/cjs/react-dom.development.js:4056:31)
at commitRootImpl (.../node_modules/react-dom/cjs/react-dom.development.js:23151:9)
at unstable_runWithPriority (.../node_modules/scheduler/cjs/scheduler.development.js:646:12) DOMException {}

at CustomConsole.error (node_modules/@testing-library/react/dist/act-compat.js:53:34)
at VirtualConsole.on.e (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:28)
at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:333:9)
at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)

console.error
The above error occurred in the <ReactTooltip> component...
    `

**Comment by mlarcher** [comment]
Everything is working fine in Chrome, but we have the same `Invalid insertion of STYLE node in #document node.` all around when running the tests. Probably the recent upgrades are using a new way of inserting style in the document, that is not known to jsdom (which is used ifor the tests by react-testing-library)

**Comment by rardoz** [comment]
Also getting the same issue when upgrading to 4.2.14

**Comment by nerfologist** [comment]
I'm still getting the error in 4.2.15 (testing with `@testing-library/react`:
```
Error: Uncaught [HierarchyRequestError: Invalid insertion of STYLE node in #document node.]

[...]

    The above error occurred in the <ReactTooltip> component:
        at ReactTooltip (/myproject/node_modules/react-tooltip/src/index.js:85:22)
        at div
        at styled.div (/myproject/node_modules/styled-components/src/models/Keyframes.js:20:51)
        at Tooltip (/myproject/src/components/Tooltip/Tooltip.js:22:20)
```

**Comment by Razielwar** [comment]
Is there any workaround as i'm stuck to test my components currently with the same error using react-tooltip 4.2.15 and testing-library/react 10.0.1

```
Error: Uncaught [HierarchyRequestError: Invalid insertion of STYLE node in #document node.]
        at reportException (/Users/xbillard/scm/discovr/discovr-front/node_modules/jest-environment-jsdom-sixteen/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
        at innerInvokeEventListeners (/Users/xbillard/scm/discovr/discovr-front/node_modules/jest-environment-jsdom-sixteen/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:333:9)
        at invokeEventListeners (/Users/xbillard/scm/discovr/discovr-front/node_modules/jest-environment-jsdom-sixteen/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
        at HTMLUnknownElementImpl._dispatch (/Users/xbillard/scm/discovr/discovr-front/node_modules/jest-environment-jsdom-sixteen/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/xbillard/scm/discovr/discovr-front/node_modules/jest-environment-jsdom-sixteen/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
        at HTMLUnknownElement.dispatchEvent (/Users/xbillard/scm/discovr/discovr-front/node_modules/jest-environment-jsdom-sixteen/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
        at Object.invokeGuardedCallbackDev (/Users/xbillard/scm/discovr/discovr-front/node_modules/react-dom/cjs/react-dom.development.js:237:16)
        at invokeGuardedCallback (/Users/xbillard/scm/discovr/discovr-front/node_modules/react-dom/cjs/react-dom.development.js:292:31)
        at commitRootImpl (/Users/xbillard/scm/discovr/discovr-front/node_modules/react-dom/cjs/react-dom.development.js:22541:9)
        at unstable_runWithPriority (/Users/xbillard/scm/discovr/discovr-front/node_modules/scheduler/cjs/scheduler.development.js:653:12) DOMException {}
```

**Comment by talyh** [comment]
@Razielwar - If you don't need anything specific from the newer versions, you can constrain the version in your `package.json` to be the latest known to not have this issue.
```
    "react-tooltip": "4.2.13", // no special characters in front of the version, to ensure an exact match
```
